//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Clothe : Product
    {
        public string Size { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
    }
}
