//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Phone : Product
    {
        public string Size { get; set; }
        public string Color { get; set; }
        public string Weight { get; set; }
        public string Chipset { get; set; }
        public string Ram { get; set; }
        public string Storage { get; set; }
    }
}
